# Generated by Django 4.2.3 on 2023-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_file_listing_poster_alter_bids_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
